spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/sanotes_notebookdb
#    username: postgres
#    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  packagesToScan: sanotesnotebookservice

---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8383