server:
  port: 8090
spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/sanotes_oauthdb
#    username: postgres
#    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

keycloak:
  custom:
    server:
      keycloak-path: /auth
    adminUser:
#      username: admin
#      password: admin
      create-admin-user-enabled: true
#    migration:
#      importProvider: singleFile
#      importLocation: classpath:sanotes-realm.json


---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8090

