keycloak:
  auth-server-url: http://localhost:8090/auth
  realm: sanotes
  resource: user-service
  credentials:
    secret: 0e082231-a70d-48e8-b8a5-fbfb743041b6
keycloakCustomProps:
  clientId: sanotes-client
#  admin-user: adminsanotes
#  admin-password: admin123

springdoc:
  packagesToScan: sanotesuserservice

---
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8585

keycloak:
  auth-server-url: http://oauth2-server:8090/auth
  realm: sanotes
  resource: user-service
  credentials:
    secret: fMMzzHDey3z9mVo6ZCxZVvleyeqdQwqS

keycloakCustomProps:
  clientId: sanotes-client
#  admin-user: adminsanotes
#  admin-password: admin123