spring:
  application:
    name: discovery-server
  config:
    import: configserver:http://localhost:8888?fail-fast=true&max-attempts=20&max-interval=3000&multiplier=1.3&initial-interval=2000

# Avoid some debugging logs at startup
logging:
  level:
    org:
      springframework:
        boot: INFO
        web: INFO
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888?fail-fast=true&max-attempts=20&max-interval=3000&multiplier=1.3&initial-interval=2000